[mcp_servers.filesystem]
args = [
    "-y",
    "@modelcontextprotocol/server-filesystem",
    "/Users/beamlak/Desktop/project_v2",
]
command = "npx"

[mcp_servers.supabase]
url = "https://mcp.supabase.com/mcp?project_ref=fgqyszbxzpmqzpqvdivx"
