import type { RoleName } from '@/types/roles';
import type { CopilotToolDefinition, CopilotToolName } from './tool-types';

const ALL_ROLES: RoleName[] = ['developer', 'admin', 'bme_head', 'technician', 'department_head', 'department_user', 'store_user', 'viewer'];
const OPERATIONAL_ROLES: RoleName[] = ['developer', 'admin', 'bme_head'];
const DEPARTMENT_ROLES: RoleName[] = ['developer', 'admin', 'bme_head', 'department_head', 'department_user'];
const TECH_ROLES: RoleName[] = ['developer', 'admin', 'bme_head', 'technician'];
const STORE_ROLES: RoleName[] = ['developer', 'admin', 'bme_head', 'store_user'];
const DEVELOPER_ONLY: RoleName[] = ['developer'];

function def(input: CopilotToolDefinition): CopilotToolDefinition {
  return input;
}

export const COPILOT_TOOL_REGISTRY: Record<CopilotToolName, CopilotToolDefinition> = {
  read_current_user_context: def({ name: 'read_current_user_context', description: 'Read signed-in user role and scope.', category: 'context', access: 'read', allowedRoles: ALL_ROLES, requiredContext: [], dataSources: ['profiles', 'user_roles'], maxRows: 1, returns: 'role and department scope', failureBehavior: 'return limited context', evidenceLabels: ['User role scope'] }),
  read_current_page_context: def({ name: 'read_current_page_context', description: 'Read lightweight page context registered by the current route.', category: 'context', access: 'read', allowedRoles: ALL_ROLES, requiredContext: [], dataSources: ['moduleContext'], maxRows: 1, returns: 'page labels, filters, visible counts, selected entity', failureBehavior: 'return empty page context', evidenceLabels: ['Current page context'] }),
  read_equipment_status: def({ name: 'read_equipment_status', description: 'Read selected equipment identity/status, or one visible critical asset when no asset is attached.', category: 'equipment', access: 'read', allowedRoles: ALL_ROLES, requiredContext: [], dataSources: ['equipment_assets', 'maintenance_events'], maxRows: 1, returns: 'equipment status and identity', failureBehavior: 'access denied or no visible equipment', evidenceLabels: ['Equipment status'] }),
  read_equipment_history: def({ name: 'read_equipment_history', description: 'Read recent maintenance history for an asset.', category: 'equipment', access: 'read', allowedRoles: [...TECH_ROLES, 'department_head', 'department_user', 'viewer'], requiredContext: ['equipmentId'], dataSources: ['maintenance_events'], maxRows: 8, returns: 'recent maintenance history', failureBehavior: 'empty history with warning', evidenceLabels: ['Maintenance history'] }),
  read_work_order_status: def({ name: 'read_work_order_status', description: 'Read selected work order status.', category: 'maintenance', access: 'read', allowedRoles: [...TECH_ROLES, 'department_head', 'viewer', 'store_user'], requiredContext: ['workOrderId'], dataSources: ['work_orders'], maxRows: 1, returns: 'work order status and linked asset', failureBehavior: 'access denied or missing context', evidenceLabels: ['Work order status'] }),
  read_request_status: def({ name: 'read_request_status', description: 'Read request status from page-selected record when available.', category: 'maintenance', access: 'read', allowedRoles: ALL_ROLES, requiredContext: [], dataSources: ['maintenance_requests', 'calibration_requests', 'training_requests', 'disposal_requests'], maxRows: 1, returns: 'request status', failureBehavior: 'return page context only', evidenceLabels: ['Request status'] }),
  read_department_readiness: def({ name: 'read_department_readiness', description: 'Read readiness snapshots scoped to role.', category: 'department', access: 'read', allowedRoles: [...DEPARTMENT_ROLES, 'viewer'], requiredContext: [], dataSources: ['clinical_readiness_snapshots'], maxRows: 8, returns: 'readiness rows', failureBehavior: 'department scope warning', evidenceLabels: ['Department readiness'] }),
  read_pm_compliance: def({ name: 'read_pm_compliance', description: 'Read PM compliance and overdue PM context.', category: 'pm', access: 'read', allowedRoles: [...TECH_ROLES, 'department_head', 'department_user', 'viewer'], requiredContext: [], dataSources: ['pm_compliance_metrics', 'v_overdue_pm'], maxRows: 12, returns: 'PM compliance/overdue rows', failureBehavior: 'empty rows with warning', evidenceLabels: ['PM compliance'] }),
  read_calibration_status: def({ name: 'read_calibration_status', description: 'Read calibration status for selected asset or triage.', category: 'calibration', access: 'read', allowedRoles: [...TECH_ROLES, 'department_head', 'department_user', 'viewer'], requiredContext: [], dataSources: ['calibration_records', 'v_calibration_due'], maxRows: 10, returns: 'calibration due/record context', failureBehavior: 'empty rows with warning', evidenceLabels: ['Calibration status'] }),
  read_stock_blockers: def({ name: 'read_stock_blockers', description: 'Read declared parts-needed blockers plus low stock and stockout rows.', category: 'inventory', access: 'read', allowedRoles: [...STORE_ROLES, 'technician', 'viewer'], requiredContext: [], dataSources: ['work_order_parts_needed', 'spare_parts', 'work_orders', 'equipment_assets', 'v_low_stock_parts'], maxRows: 10, returns: 'stock blockers', failureBehavior: 'empty rows with warning', evidenceLabels: ['Stock blockers'] }),
  read_procurement_pipeline: def({ name: 'read_procurement_pipeline', description: 'Read procurement pipeline.', category: 'procurement', access: 'read', allowedRoles: [...STORE_ROLES, 'viewer'], requiredContext: [], dataSources: ['procurement_requests'], maxRows: 10, returns: 'procurement rows', failureBehavior: 'empty rows with warning', evidenceLabels: ['Procurement pipeline'] }),
  read_training_status: def({ name: 'read_training_status', description: 'Read training request status.', category: 'training', access: 'read', allowedRoles: [...DEPARTMENT_ROLES, 'technician', 'viewer'], requiredContext: [], dataSources: ['training_requests'], maxRows: 10, returns: 'training request rows', failureBehavior: 'empty rows with warning', evidenceLabels: ['Training status'] }),
  read_disposal_status: def({ name: 'read_disposal_status', description: 'Read disposal request status.', category: 'disposal', access: 'read', allowedRoles: [...DEPARTMENT_ROLES, 'viewer'], requiredContext: [], dataSources: ['disposal_requests'], maxRows: 10, returns: 'disposal rows', failureBehavior: 'empty rows with warning', evidenceLabels: ['Disposal status'] }),
  read_replacement_risk: def({ name: 'read_replacement_risk', description: 'Read replacement risk scores.', category: 'replacement', access: 'read', allowedRoles: [...OPERATIONAL_ROLES, 'viewer'], requiredContext: [], dataSources: ['replacement_priority_scores', 'v_replacement_decision'], maxRows: 10, returns: 'replacement candidate rows', failureBehavior: 'empty rows with warning', evidenceLabels: ['Replacement risk'] }),
  read_command_center_snapshot: def({ name: 'read_command_center_snapshot', description: 'Read cross-module command center context.', category: 'command', access: 'read', allowedRoles: [...OPERATIONAL_ROLES, 'viewer'], requiredContext: [], dataSources: ['work_orders', 'maintenance_requests', 'equipment_assets', 'equipment_risk_scores', 'v_calibration_due', 'v_overdue_pm', 'work_order_parts_needed', 'spare_parts', 'procurement_requests', 'training_requests', 'triage_action_queue'], maxRows: 20, returns: 'operational priority snapshot', failureBehavior: 'partial snapshot', evidenceLabels: ['Command Center snapshot'] }),
  read_alerts_summary: def({ name: 'read_alerts_summary', description: 'Read active Notification Center recommendation signals. Tool name is retained for legacy Copilot plans.', category: 'notifications', access: 'read', allowedRoles: ALL_ROLES, requiredContext: [], dataSources: ['recommendation_flags'], maxRows: 12, returns: 'active notification signal summary', failureBehavior: 'empty rows with warning', evidenceLabels: ['Notification summary'] }),
  read_qr_asset_context: def({ name: 'read_qr_asset_context', description: 'Read QR asset context without exposing raw tokens unnecessarily.', category: 'qr', access: 'read', allowedRoles: ALL_ROLES, requiredContext: [], dataSources: ['equipment_assets'], maxRows: 1, returns: 'QR lifecycle and selected asset context', failureBehavior: 'limited QR context', evidenceLabels: ['QR asset context'] }),
  read_qr_scan_evidence: def({ name: 'read_qr_scan_evidence', description: 'Read QR scan evidence for privileged roles.', category: 'qr', access: 'read', allowedRoles: OPERATIONAL_ROLES, requiredContext: [], dataSources: ['equipment_qr_scans'], maxRows: 10, returns: 'scan evidence', failureBehavior: 'access denied for non-operational roles', evidenceLabels: ['QR scan evidence'] }),
  read_offline_sync_summary: def({ name: 'read_offline_sync_summary', description: 'Read offline sync summary and conflicts.', category: 'offline', access: 'read', allowedRoles: ALL_ROLES, requiredContext: [], dataSources: ['offline_sync_events', 'moduleContext.queueStatus'], maxRows: 20, returns: 'offline queue/conflict summary', failureBehavior: 'page context only', evidenceLabels: ['Offline sync summary'] }),
  read_report_snapshot: def({ name: 'read_report_snapshot', description: 'Read current report type and evidence links.', category: 'reports', access: 'read', allowedRoles: ALL_ROLES, requiredContext: [], dataSources: ['moduleContext.reportType'], maxRows: 1, returns: 'report snapshot context', failureBehavior: 'page context only', evidenceLabels: ['Report snapshot'] }),
  read_copilot_telemetry_summary: def({ name: 'read_copilot_telemetry_summary', description: 'Read copilot telemetry aggregate.', category: 'developer', access: 'read', allowedRoles: DEVELOPER_ONLY, requiredContext: [], dataSources: ['chat_telemetry_events'], maxRows: 20, returns: 'telemetry summary', failureBehavior: 'developer-only denied', evidenceLabels: ['Copilot telemetry'] }),
  read_gemini_usage_summary: def({ name: 'read_gemini_usage_summary', description: 'Read app-tracked Gemini usage summary.', category: 'usage', access: 'read', allowedRoles: OPERATIONAL_ROLES, requiredContext: [], dataSources: ['copilot_usage_events'], maxRows: 20, returns: 'usage summary', failureBehavior: 'own usage only for non-privileged users', evidenceLabels: ['App-tracked Gemini usage'] }),
  read_tool_trace: def({ name: 'read_tool_trace', description: 'Developer-only tool trace.', category: 'developer', access: 'read', allowedRoles: DEVELOPER_ONLY, requiredContext: [], dataSources: ['chat_telemetry_events.metadata'], maxRows: 10, returns: 'tool trace', failureBehavior: 'developer-only denied', evidenceLabels: ['Tool trace'] }),
  read_routing_trace: def({ name: 'read_routing_trace', description: 'Developer-only routing trace.', category: 'developer', access: 'read', allowedRoles: DEVELOPER_ONLY, requiredContext: [], dataSources: ['chat_telemetry_events.classifier_candidates'], maxRows: 10, returns: 'routing trace', failureBehavior: 'developer-only denied', evidenceLabels: ['Routing trace'] }),
  read_provider_trace: def({ name: 'read_provider_trace', description: 'Developer-only provider metadata.', category: 'developer', access: 'read', allowedRoles: DEVELOPER_ONLY, requiredContext: [], dataSources: ['chat_telemetry_events.metadata.providerMetadata'], maxRows: 10, returns: 'provider metadata', failureBehavior: 'developer-only denied', evidenceLabels: ['Provider trace'] }),
  read_parser_failures: def({ name: 'read_parser_failures', description: 'Developer-only parser failures.', category: 'developer', access: 'read', allowedRoles: DEVELOPER_ONLY, requiredContext: [], dataSources: ['chat_telemetry_events'], maxRows: 10, returns: 'parser recovery/failure rows', failureBehavior: 'developer-only denied', evidenceLabels: ['Parser failures'] }),
  read_copilot_usage_events: def({ name: 'read_copilot_usage_events', description: 'Developer-only raw usage event inspection.', category: 'developer', access: 'read', allowedRoles: DEVELOPER_ONLY, requiredContext: [], dataSources: ['copilot_usage_events'], maxRows: 20, returns: 'usage events', failureBehavior: 'developer-only denied', evidenceLabels: ['Usage events'] }),
  run_gemini_smoke_test: def({ name: 'run_gemini_smoke_test', description: 'Developer-only smoke test descriptor. Execution stays in server action.', category: 'developer', access: 'read', allowedRoles: DEVELOPER_ONLY, requiredContext: [], dataSources: ['Gemini provider config'], maxRows: 1, returns: 'smoke test availability', failureBehavior: 'developer-only denied', evidenceLabels: ['Gemini smoke test'] }),
  // Phase 2 — record-level + workflow tools
  read_maintenance_request_status: def({ name: 'read_maintenance_request_status', description: 'Read a single maintenance request with linked work orders, requester, asset, reported condition, and condition trace.', category: 'maintenance', access: 'read', allowedRoles: [...TECH_ROLES, 'department_head', 'department_user', 'store_user', 'viewer'], requiredContext: [], dataSources: ['maintenance_requests', 'work_orders', 'equipment_assets', 'profiles'], maxRows: 1, returns: 'maintenance request detail', failureBehavior: 'page context only', evidenceLabels: ['Maintenance request status'] }),
  read_pm_schedule_evidence: def({ name: 'read_pm_schedule_evidence', description: 'Read a PM schedule with plan, asset, assigned technician, completion evidence, and compliance impact.', category: 'pm', access: 'read', allowedRoles: [...TECH_ROLES, 'department_head', 'department_user', 'viewer'], requiredContext: [], dataSources: ['pm_schedules', 'pm_plans', 'pm_completions', 'equipment_assets', 'v_overdue_pm'], maxRows: 1, returns: 'PM schedule evidence', failureBehavior: 'page context only', evidenceLabels: ['PM schedule evidence'] }),
  read_calibration_request_evidence: def({ name: 'read_calibration_request_evidence', description: 'Read a calibration request and its latest linked calibration record (if any).', category: 'calibration', access: 'read', allowedRoles: [...TECH_ROLES, 'department_head', 'department_user', 'viewer'], requiredContext: [], dataSources: ['calibration_requests', 'calibration_records', 'equipment_assets', 'calibration_types'], maxRows: 1, returns: 'calibration request evidence', failureBehavior: 'page context only', evidenceLabels: ['Calibration request evidence'] }),
  read_calibration_record_evidence: def({ name: 'read_calibration_record_evidence', description: 'Read a calibration record (result, dates, certificate) and any open follow-up request.', category: 'calibration', access: 'read', allowedRoles: [...TECH_ROLES, 'department_head', 'department_user', 'viewer'], requiredContext: [], dataSources: ['calibration_records', 'calibration_requests', 'equipment_assets'], maxRows: 1, returns: 'calibration record evidence', failureBehavior: 'page context only', evidenceLabels: ['Calibration record evidence'] }),
  read_report_data: def({ name: 'read_report_data', description: 'Read canonical KPI snapshot for the currently viewed report using buildReportKPIs + canonical-metrics.', category: 'reports', access: 'read', allowedRoles: ALL_ROLES, requiredContext: ['reportType'], dataSources: ['canonical-metrics', 'reports.service'], maxRows: 1, returns: 'report KPI summary', failureBehavior: 'page context only when canonical metrics are not available', evidenceLabels: ['Report KPI data'] }),
  read_notification_delivery_status: def({ name: 'read_notification_delivery_status', description: 'Read notification + deliveries + Telegram status for a specific recipient row.', category: 'notifications', access: 'read', allowedRoles: ALL_ROLES, requiredContext: [], dataSources: ['notifications', 'notification_deliveries', 'notification_events'], maxRows: 1, returns: 'notification delivery status', failureBehavior: 'own-row read only for non-privileged roles', evidenceLabels: ['Notification delivery status'] }),
  read_telegram_eligibility: def({ name: 'read_telegram_eligibility', description: 'Explain Telegram delivery eligibility: env enabled, monitor enabled, recipient connection, event eligibility.', category: 'notifications', access: 'read', allowedRoles: ALL_ROLES, requiredContext: [], dataSources: ['telegram_connections', 'notification_events', 'notification_deliveries'], maxRows: 1, returns: 'telegram eligibility evaluation', failureBehavior: 'limited evaluation when env is hidden', evidenceLabels: ['Telegram eligibility'] }),
  read_notification_rule_logs: def({ name: 'read_notification_rule_logs', description: 'Read the most recent notification rule check runs with per-scan results.', category: 'notifications', access: 'read', allowedRoles: OPERATIONAL_ROLES, requiredContext: [], dataSources: ['notification_rule_logs'], maxRows: 10, returns: 'notification rule logs', failureBehavior: 'empty when no logs exist', evidenceLabels: ['Notification rule logs'] }),
  read_qr_coverage_status: def({ name: 'read_qr_coverage_status', description: 'Read QR coverage status across equipment_assets + scan evidence aggregates.', category: 'qr', access: 'read', allowedRoles: OPERATIONAL_ROLES, requiredContext: [], dataSources: ['equipment_assets', 'equipment_qr_scans'], maxRows: 1, returns: 'QR coverage aggregate', failureBehavior: 'partial when scan table is empty', evidenceLabels: ['QR coverage status'] }),
  read_validation_readiness: def({ name: 'read_validation_readiness', description: 'Read validation-readiness service result (fixture probes, role integrity, environment warnings).', category: 'developer', access: 'read', allowedRoles: OPERATIONAL_ROLES, requiredContext: [], dataSources: ['validation-readiness.service', 'developer-lab.service'], maxRows: 1, returns: 'validation readiness summary', failureBehavior: 'partial when probes are unavailable', evidenceLabels: ['Validation readiness'] }),
};

export function getCopilotToolDefinition(name: CopilotToolName) {
  return COPILOT_TOOL_REGISTRY[name];
}

export function listCopilotToolDefinitions() {
  return Object.values(COPILOT_TOOL_REGISTRY);
}
