-- Migration 00045: Equipment QR Identity Foundation (Phase 1)
--
-- Establishes a stable, secure, database-backed QR identity for every
-- equipment asset using random QR tokens (not asset_code or asset UUID).
--
-- Phase 1 scope:
--   - Add QR token + label lifecycle metadata fields to equipment_assets
--   - Create equipment_qr_scans audit table for future scan logging
--   - Conservative RLS policies (admin/developer/bme_head readable; authenticated insert)
--   - No automatic token generation in SQL; tokens are generated by the
--     application service layer (src/services/qr.service.ts).
--
-- Token strategy:
--   - Random URL-safe string prefixed with "qra_".
--   - Token identifies the physical asset; it does NOT grant permission.
--   - Auth/session + RBAC still control what the scanner can see/do.

-- =============================================================================
-- equipment_assets: QR identity columns
-- =============================================================================

ALTER TABLE equipment_assets
  ADD COLUMN IF NOT EXISTS qr_token                  TEXT,
  ADD COLUMN IF NOT EXISTS qr_generated_at           TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS qr_label_status           TEXT NOT NULL DEFAULT 'not_generated',
  ADD COLUMN IF NOT EXISTS qr_label_printed_at       TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS qr_label_attached_at      TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS qr_label_replaced_at      TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS qr_token_regenerated_at   TIMESTAMPTZ;

-- Label lifecycle status check
ALTER TABLE equipment_assets
  DROP CONSTRAINT IF EXISTS equipment_assets_qr_label_status_check;

ALTER TABLE equipment_assets
  ADD CONSTRAINT equipment_assets_qr_label_status_check
  CHECK (qr_label_status IN (
    'not_generated',
    'generated',
    'printed',
    'attached',
    'needs_replacement',
    'revoked'
  ));

-- Unique index on qr_token where present (partial unique allows many NULLs).
CREATE UNIQUE INDEX IF NOT EXISTS idx_equipment_assets_qr_token_unique
  ON equipment_assets (qr_token)
  WHERE qr_token IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_equipment_assets_qr_label_status
  ON equipment_assets (qr_label_status);

CREATE INDEX IF NOT EXISTS idx_equipment_assets_qr_generated_at
  ON equipment_assets (qr_generated_at);

COMMENT ON COLUMN equipment_assets.qr_token IS
  'Random URL-safe QR identity token (prefix qra_). Lookup key only; does not grant permission. Generated by application service layer.';
COMMENT ON COLUMN equipment_assets.qr_label_status IS
  'QR label lifecycle: not_generated | generated | printed | attached | needs_replacement | revoked.';
COMMENT ON COLUMN equipment_assets.qr_generated_at IS
  'Timestamp the current qr_token was generated.';
COMMENT ON COLUMN equipment_assets.qr_label_printed_at IS
  'Timestamp the current QR label was last marked printed.';
COMMENT ON COLUMN equipment_assets.qr_label_attached_at IS
  'Timestamp the current QR label was last marked attached to the physical asset.';
COMMENT ON COLUMN equipment_assets.qr_label_replaced_at IS
  'Timestamp the prior QR token was retired (typically set when regenerating).';
COMMENT ON COLUMN equipment_assets.qr_token_regenerated_at IS
  'Timestamp the qr_token was last regenerated (token rotation).';

-- =============================================================================
-- equipment_qr_scans: scan audit table
-- =============================================================================

CREATE TABLE IF NOT EXISTS equipment_qr_scans (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  asset_id        UUID NOT NULL REFERENCES equipment_assets(id) ON DELETE CASCADE,
  scanned_by      UUID REFERENCES profiles(id) ON DELETE SET NULL,
  role_name       TEXT,
  scanned_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  scan_source     TEXT NOT NULL DEFAULT 'web',
  user_agent      TEXT,
  online_status   TEXT NOT NULL DEFAULT 'online',
  action_taken    TEXT,
  metadata        JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT equipment_qr_scans_scan_source_check
    CHECK (scan_source IN ('web', 'mobile', 'pwa', 'unknown')),
  CONSTRAINT equipment_qr_scans_online_status_check
    CHECK (online_status IN ('online', 'offline_queued', 'synced_later', 'unknown'))
);

COMMENT ON TABLE equipment_qr_scans IS
  'Audit trail of QR scans against equipment assets. Written by future Phase 6 scan logging. Not publicly readable.';
COMMENT ON COLUMN equipment_qr_scans.scan_source IS
  'web | mobile | pwa | unknown — origin of the scan request.';
COMMENT ON COLUMN equipment_qr_scans.online_status IS
  'online | offline_queued | synced_later | unknown — connectivity state when the scan was logged.';
COMMENT ON COLUMN equipment_qr_scans.action_taken IS
  'Optional free-form label for the role-aware action the scanner took (e.g. view, create_request).';
COMMENT ON COLUMN equipment_qr_scans.metadata IS
  'Free-form JSON envelope for future scan-context payload. Must never contain credentials.';

CREATE INDEX IF NOT EXISTS idx_equipment_qr_scans_asset
  ON equipment_qr_scans (asset_id);
CREATE INDEX IF NOT EXISTS idx_equipment_qr_scans_scanned_by
  ON equipment_qr_scans (scanned_by);
CREATE INDEX IF NOT EXISTS idx_equipment_qr_scans_scanned_at
  ON equipment_qr_scans (scanned_at DESC);
CREATE INDEX IF NOT EXISTS idx_equipment_qr_scans_role
  ON equipment_qr_scans (role_name);
CREATE INDEX IF NOT EXISTS idx_equipment_qr_scans_online_status
  ON equipment_qr_scans (online_status);

-- =============================================================================
-- RLS policies for equipment_qr_scans
-- =============================================================================
-- Conservative defaults aligned with auth_user_has_role pattern used elsewhere:
--   - Read: developer / admin / bme_head, OR the scanner reading their own rows.
--   - Insert: any authenticated user (writes are funneled through the server
--     action layer so role gating still applies at the application boundary).
--   - Update / Delete: not granted to anyone via RLS at this time.
-- This may be tightened further once scan logging UI lands in Phase 6.

ALTER TABLE equipment_qr_scans ENABLE ROW LEVEL SECURITY;

CREATE POLICY equipment_qr_scans_select
  ON equipment_qr_scans
  FOR SELECT
  TO authenticated
  USING (
    auth_user_has_role('developer')
    OR auth_user_has_role('admin')
    OR auth_user_has_role('bme_head')
    OR scanned_by IN (SELECT id FROM profiles WHERE user_id = auth.uid())
  );

CREATE POLICY equipment_qr_scans_insert
  ON equipment_qr_scans
  FOR INSERT
  TO authenticated
  WITH CHECK (true);
